steps:
- id: checkout-pr-branch
  name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args: [
      './helpers/init_git_repo.sh',
  ]
  env: [
           'COMMIT_SHA=${COMMIT_SHA}',
           'BASE_REPO_URL=https://github.com/jaketf/ci-cd-for-data-processing-workflow.git',
           'BASE_BRANCH=${_BASE_BRANCH}',
           'PR_NUMBER=${_PR_NUMBER}',
  ]
- id: run-style-and-unit-tests
  name: gcr.io/${PROJECT_ID}/make
  args: [test]
  waitFor: [checkout-pr-branch]
- id: run-relevant-cloud-builds
  name: google/cloud-sdk
  waitFor: [checkout-pr-branch]
  entrypoint: 'bash'
  args: ['./helpers/run_relevant_cloudbuilds.sh', 'cloudbuild.yaml']
